export const INSTRUMENTS = {

Forex: [
"EURUSD","GBPUSD","USDJPY","USDCHF","USDCAD","AUDUSD","NZDUSD",
"EURGBP","EURJPY","EURCHF","EURCAD","EURAUD","EURNZD",
"GBPJPY","GBPCHF","GBPCAD","GBPAUD","GBPNZD",
"AUDJPY","AUDCHF","AUDCAD","AUDNZD",
"NZDJPY","NZDCHF","NZDCAD",
"CADJPY","CADCHF","CHFJPY"
],

Crypto: [
"BTCUSD","ETHUSD","SOLUSD","BNBUSD","XRPUSD","ADAUSD","DOGEUSD",
"AVAXUSD","DOTUSD","LINKUSD","LTCUSD","BCHUSD","MATICUSD",
"ATOMUSD","NEARUSD","APTUSD","OPUSD","ARBUSD"
],

Indices: [
"NAS100","SPX500","US30","DAX40","FTSE100","CAC40","NIKKEI225",
"HK50","AUS200","STOXX50"
],

Commodities: [
"XAUUSD","XAGUSD","XPTUSD","XPDUSD",
"WTI","BRENT","NATGAS",
"COPPER","ALUMINUM","NICKEL",
"WHEAT","CORN","SOYBEAN","COFFEE","SUGAR"
],

Futures: [
"ES","NQ","YM","RTY",
"CL","NG","GC","SI",
"HG","ZC","ZW","ZS",
"6E","6B","6J","6A","6C"
],

Stocks: [
"AAPL","MSFT","NVDA","AMZN","GOOGL","META","TSLA","NFLX",
"AMD","INTC","PLTR","COIN","SMCI","AVGO","CRM",
"JPM","BAC","GS","V","MA",
"WMT","COST","HD","LOW","NKE",
"SPY","QQQ","IWM","DIA"
]

}